import type { Service } from "@/lib/types";

export const servicesSeed: Service[] = [
  {
    id: "svc_ai-automation",
    slug: "ai-automation",
    name: "AI Automation",
    shortDescription: "Let AI handle the repetitive work your team shouldn't have to.",
    description:
      "We connect your existing tools so leads, bookings, follow-ups, and paperwork move on their own — no more copy-pasting between apps or chasing customers by hand.",
    outcomes: [
      "Save hours every week on manual tasks",
      "Nothing falls through the cracks",
      "Your team focuses on customers, not admin work",
    ],
    icon: "Workflow",
    availability: "live",
    status: "published",
    order: 1,
  },
  {
    id: "svc_ai-chatbots",
    slug: "ai-chatbots",
    name: "AI Chatbots",
    shortDescription: "Answer every customer question, day or night.",
    description:
      "A friendly assistant on your website and socials that answers questions, qualifies leads, and books appointments — even while you sleep.",
    outcomes: ["Never miss a customer message", "Available 24/7", "More bookings without more staff"],
    icon: "MessageCircle",
    availability: "live",
    status: "published",
    order: 2,
  },
  {
    id: "svc_website-landing-pages",
    slug: "website-landing-pages",
    name: "Website & Landing Pages",
    shortDescription: "A fast, modern site that turns visitors into customers.",
    description:
      "We design and build websites and landing pages that load fast, look great on any phone, and are built to convert visitors into booked calls or sales.",
    outcomes: ["A site you're proud to share", "Built for mobile from day one", "Clear paths to contact you"],
    icon: "Globe",
    availability: "live",
    status: "published",
    order: 3,
  },
  {
    id: "svc_ai-ugc-ads",
    slug: "ai-ugc-ads",
    name: "AI UGC Ads",
    shortDescription: "Scroll-stopping ad creative, made fast.",
    description:
      "AI-assisted, creator-style video and image ads for Instagram, TikTok, and Facebook — made quickly and affordably, without a full production shoot.",
    outcomes: ["Fresh creative without a film crew", "Faster turnaround on new ad ideas", "Content built for social, not repurposed"],
    icon: "Clapperboard",
    availability: "live",
    status: "published",
    order: 4,
  },
  {
    id: "svc_business-consulting",
    slug: "business-consulting",
    name: "Business Consulting",
    shortDescription: "A clear plan for where AI actually helps your business.",
    description:
      "We look at how your business runs today and show you exactly where automation and AI will save time or make money — no jargon, just a plan.",
    outcomes: ["A written plan you can act on", "No pressure to buy more than you need", "Explained in plain business terms"],
    icon: "Compass",
    availability: "live",
    status: "published",
    order: 5,
  },
  {
    id: "svc_ai-voice-agents",
    slug: "ai-voice-agents",
    name: "AI Voice Agents",
    shortDescription: "A phone assistant that answers every call.",
    description:
      "An AI receptionist that answers your business phone line, handles common questions, and books appointments — coming soon to Nexora.",
    outcomes: [],
    icon: "Phone",
    availability: "coming-soon",
    status: "published",
    order: 6,
  },
  {
    id: "svc_ai-calling-systems",
    slug: "ai-calling-systems",
    name: "AI Calling Systems",
    shortDescription: "Outbound calls that follow up automatically.",
    description:
      "Automated, natural-sounding follow-up calls for reminders and re-engagement — coming soon to Nexora.",
    outcomes: [],
    icon: "PhoneCall",
    availability: "coming-soon",
    status: "published",
    order: 7,
  },
  {
    id: "svc_ai-sales-agents",
    slug: "ai-sales-agents",
    name: "AI Sales Agents",
    shortDescription: "An assistant that nurtures leads for you.",
    description:
      "An AI that follows up with leads, answers objections, and moves people toward booking — coming soon to Nexora.",
    outcomes: [],
    icon: "TrendingUp",
    availability: "coming-soon",
    status: "published",
    order: 8,
  },
  {
    id: "svc_ai-employees",
    slug: "ai-employees",
    name: "AI Employees",
    shortDescription: "A full digital team member for your business.",
    description:
      "A combined AI worker that handles messaging, scheduling, and follow-up across every channel — coming soon to Nexora.",
    outcomes: [],
    icon: "Users",
    availability: "coming-soon",
    status: "published",
    order: 9,
  },
];
